// Wails runtime bindings - these will be generated by `wails dev`
// For type safety, we define the interfaces here

export interface WailsRuntime {
  EventsOn(eventName: string, callback: (...data: any[]) => void): () => void;
  EventsOff(eventName: string, ...additionalEventNames: string[]): void;
  EventsEmit(eventName: string, ...data: any[]): void;
}

// During development, the wails runtime is injected globally
declare global {
  interface Window {
    runtime: WailsRuntime;
    go: Record<string, Record<string, (...args: any[]) => Promise<any>>>;
  }
}
